s = ";;;;Hello World;;;;"
print(len(s))
x = 12345
y = str(x)
print(y.find("3"))
print(y)
print(s.upper())
print(s.count("l"))
print(s.count("l", 1, 5))
print(s.lower())
print(s.split())
print(s.split("l"))
print(s.replace("World", "Python", 2))
print(s.startswith("Hello"))
print(s.endswith("Python"))
print(s.strip(';2'))
print(s.index("l"))
print(s.index("el", 1, 7))
print(s.lstrip(';7 \''))
print(s.rstrip(';7 \''))